### ISSUE TITLE
sync below 113 bpm seems to break mod rate (beta firmware)

### ISSUE THREAD

**Issue by pssssssst** [Befaco/Oneiroi#10]
Hi, weird bug here. I hope someone can confirm.
- I'm sending a sync trigger every measure on 112bpm (every 2,x seconds) or lower.
- Mod type is on square wave
- I turn the speed knob counter clock wise (11 o'clock or lower)
- the mod output is allways high, it doesn't go down

Turning the speed up to 113bpm or higher, i get the expected behavior
The different waveforms all behave a little different. but the cycling ones (sine/ramp/saw/pulse) stay on whatever is their first value.

**Comment by hirnlego** [comment]
Cannot reproduce... I'm trying with a sync of 30 BPM (the minimum supported by the module) and I have no problem with the lowest modulation speed and any shape. Are you certain that Oneiroi is not receiving a clock lower than 20 BPM?

**Comment by pssssssst** [comment]
does a sync of 30bpm translate to a sync pulse every 2 seconds?

**Comment by hirnlego** [comment]
@pssssssst yes.

**Comment by pssssssst** [comment]
Okay, so then everything works as expected. 
I thought sync triggers could go as slow as one cycle of the buffer takes.

**Comment by hirnlego** [comment]
@pssssssst no... 30 BPM is the minimum because of how the tempo detection works in Oneiroi. You can try with lower tempo, but there's no guarantee that the module keeps up with it.
Keep in mind that with 30 BPM and the lowest modulation speed you can achieve something like 0.5 BPM as tempo for the modulation.
